# Generated by Django 3.1 on 2021-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text_description', models.CharField(default=None, max_length=200)),
                ('more_info', models.CharField(default=None, max_length=2000)),
                ('product_image', models.ImageField(default=None, upload_to='uploads/')),
                ('video', models.FileField(default=None, upload_to='uploads/')),
                ('link_1', models.URLField(default=None)),
                ('link_2', models.URLField(default=None)),
            ],
        ),
    ]
