# Generated by Django 3.1.4 on 2021-01-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20210129_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
