# Generated by Django 3.1.4 on 2021-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('more_counter', models.IntegerField(default=0)),
                ('readmore_counter', models.IntegerField(default=0)),
                ('video_counter', models.IntegerField(default=0)),
                ('end_time', models.DateTimeField()),
                ('duration', models.DateTimeField()),
            ],
        ),
    ]
