# Generated by Django 3.1.4 on 2021-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_session_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.CharField(max_length=300),
        ),
    ]
