# Generated by Django 3.1 on 2021-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20210130_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='played_videos',
            field=models.IntegerField(default=0),
        ),
    ]
