# Generated by Django 3.1 on 2021-02-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_session_played_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='links_counter',
            field=models.IntegerField(default=0),
        ),
    ]
